### ISSUE TITLE
레포명 바꿔주세요

### ISSUE THREAD

**Issue by Ryulth** [devSoyoung/work-life-bell-app#2]
https://github.com/devSoyoung/off-the-work-app/blob/4095b769f5cf72ce8f0c60aa1be0c91b99e1f897/app.json

https://github.com/devSoyoung/off-the-work-app/blob/f38b6e39b4ab8524a6bff3c522ca977c03b9ce8d/src/layouts/AppHeader.tsx

여기에 있는 앱명도 바꿔주세요 👍

**Comment by devSoyoung** [comment]
@Ryulth 레포명 바꿨읍니다 :)
앱 이름도 나중에 바꿀게요~
